### ISSUE TITLE
Other targets?

### ISSUE THREAD

**Issue by Lelelo1** [back2dos/embed-js#2]
Is it possible to run the embedded js, on targets like java and C#?

**Comment by back2dos** [comment]
In theory, everything is possible. AFAIK some JVMs (e.g. Graal) and the CLR allow evaluating JavaScript. It might be possible to expand the code from this library to not only embed the JavaScript, but also wrap it into the necessary code to evaluate it. If you feel like investigating this, PRs are welcome, but from my end it's not something I have the time to implement in the foreseeable future.
